spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    hikari:
      jdbc-url: jdbc:h2:mem:test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
